# Generated by Django 4.2.6 on 2023-10-21 00:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('payment', models.CharField(choices=[('carta', 'Carta orqali'), ('naqd', 'Naqd pul orqali'), ('kredit_karta', 'Kredit karta orqali'), ('bank', 'Bank orqali'), ('paypal', 'PayPal orqali')], max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
